### ISSUE TITLE
few tests are failing

### ISSUE THREAD

**Issue by hyzhak** [jprichardson/cb-insight#3]
Hey guys, I have tried to launch tests of your modules but they has failed to me. Is everything fine with this module or I'm doing something wrong?

steps to reproduce:

``` bash
$ npm install && npm test

npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
async@0.9.2 node_modules/async

decimal.js@4.0.3 node_modules/decimal.js

cb-tester@0.1.14 node_modules/cb-tester
└── bitcoinjs-lib@1.5.8 (randombytes@2.0.1, ecurve@1.0.2, bigi@1.4.1, create-hmac@1.1.4, typeforce@1.5.5, bs58check@1.0.6, create-hash@1.1.2)

nock@0.53.0 node_modules/nock
├── propagate@0.3.1
├── debug@1.0.4 (ms@0.6.2)
└── lodash@2.4.1

mocha@2.3.4 node_modules/mocha
├── escape-string-regexp@1.0.2
├── growl@1.8.1
├── supports-color@1.2.0
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

superagent@0.21.0 node_modules/superagent
├── extend@1.2.1
├── methods@1.0.1
├── cookiejar@2.0.1
├── component-emitter@1.1.2
├── reduce-component@1.0.1
├── qs@1.2.0
├── mime@1.2.11
├── debug@2.2.0 (ms@0.7.1)
├── formidable@1.0.14
├── form-data@0.1.3 (combined-stream@0.0.7)
└── readable-stream@1.0.27-1 (inherits@2.0.1, string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)

> cb-insight@0.1.0 test /Users/hyzhak/IdeaProjects/coinspace/cb-insight
> mocha --reporter spec --timeout 15000 --grep "Addresses Summary|Unspents|Propagate|addresses unspents"



  addresses
    unspents
      > when output is a fraction that when JS multiplied by 1e8 is still a fraction
        ✓ should correct the behavior and produce an integer

  cb-tests
    Addresses
      Summary
        ✓ returns summary for mpNDUWcDcZw1Teo3LFHvr8usNdwDLKdTaY (1132ms)
        ✓ returns summary for mv3fK2ME7g9K4HswGXs6mG92e7gRgsTsqM (841ms)
        ✓ returns summary for mvJCbQvE6DgVAECMwDprASP3NMwuU53Eie (800ms)
        ✓ returns summary for mvwvsPT2J3VPEaYmFdExFc4iBGRRK2Vdkd (400ms)
        1) throws on XXXXUWcDcZw1Teo3LFHvr8usNdwDLKXXXX
        ✓ works for scriptHash addresses (819ms)
        ✓ works for n of 202 addresses (5426ms)
      Unspents
        ✓ returns sane results (408ms)
        2) throws on XXXXUWcDcZw1Teo3LFHvr8usNdwDLKXXXX
        ✓ returns expected transactions (414ms)
        ✓ works for n of 202 addresses (4592ms)
    Blocks
      Propagate
        - throws on malformed block
    Transactions
      Propagate
        3) propagates a single Transaction
        4) works for n > 1 transactions
        - throws on malformed transaction


  10 passing (16s)
  2 pending
  4 failing

  1) cb-tests Addresses Summary throws on XXXXUWcDcZw1Teo3LFHvr8usNdwDLKXXXX:
     Uncaught Error: non-ok http status code
      at lib/addresses.js:21:36
      at Request.callback (node_modules/superagent/lib/node/index.js:748:3)
      at Request.<anonymous> (node_modules/superagent/lib/node/index.js:135:10)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:938:12)
      at _stream_readable.js:908:16

  2) cb-tests Addresses Unspents throws on XXXXUWcDcZw1Teo3LFHvr8usNdwDLKXXXX:
     Uncaught Error: non-ok http status code
      at lib/addresses.js:54:36
      at Request.callback (node_modules/superagent/lib/node/index.js:748:3)
      at Request.<anonymous> (node_modules/superagent/lib/node/index.js:135:10)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:938:12)
      at _stream_readable.js:908:16

  3) cb-tests Transactions Propagate propagates a single Transaction:
     Uncaught Error: getaddrinfo ENOTFOUND testnet.helloblock.io
      at errnoException (dns.js:44:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

  4) cb-tests Transactions Propagate works for n > 1 transactions:
     Uncaught Error: getaddrinfo ENOTFOUND testnet.helloblock.io
      at errnoException (dns.js:44:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)



npm ERR! Test failed.  See above for more details.

```

**Comment by jprichardson** [comment]
No, you didn't do anything wrong.

Tests 1 and 2 are failing because `XXXXUWcDcZw1Teo3LFHvr8usNdwDLKXXXX` is an invalid address and now Bitpay Insight returns a non 2xx http code to warn you - the tests haven't been updated to reflect that.

Tests 3 and 4 are failing because helloblock.io has shutdown.

I'll leave this open to remind me for tests 1 and 2.

**Comment by hyzhak** [comment]
@jprichardson thanks for quick response

**Comment by hyzhak** [comment]
btw why do you use `"cb-tester": "^0.1.11"` but not actual `0.2.x` version?

**Comment by jprichardson** [comment]
> btw why do you use "cb-tester": "^0.1.11" but not actual 0.2.x version?

I haven't updated the module to test with `0.2.x` yet.

**Comment by hyzhak** [comment]
@jprichardson yes, it is sad news about helloblock. Btw new version of cb-tester uses blocktrail.com instead

**Comment by dcousens** [comment]
@hyzhak `cb-tester` should be agnostic?

**Comment by hyzhak** [comment]
@dcousens You right! Good point! You can have default endpoints, but it should be changeable.
